### ISSUE TITLE
Translate optional_postgresql_installation folder

### ISSUE THREAD

**Issue by malon** [PyAr/djangogirls-tutorial-extensions-es#6]

**Comment by erickgnavar** [comment]
Tengo la traducción casi lista, solo tengo una duda con una frase
Great - that's databases all sorted!
No logro entender el significado 😢

**Comment by humitos** [comment]
No dejes de hacer el PR igual con ese comentario en la descripción . Luego le vas agregando commits a medida que vamos coordinando.

**Comment by humitos** [comment]
Nunca vi esa expresión. Sin embargo, me suena a que es algo así como:
- Genial - eso es todo lo que necesitamos saber sobre base de datos
- Genial - eso es lo que nos importa acerca de las base de datos

**Comment by erickgnavar** [comment]
Ya hice el PR, me parece que por ahi va la expresión, seria cuestión de decidir que traducción usar.

**Comment by humitos** [comment]
https://twitter.com/ramiromorales/status/696537402567954432

**Comment by erickgnavar** [comment]
Ya actualicé la traducción 😃

**Comment by humitos** [comment]
Hecho en #11
